apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voiceresumeapp-ingress
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - voiceresumeapp.example.com
    secretName: voiceresumeapp-tls
  rules:
  - host: voiceresumeapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voiceresumeapp-svc
            port:
              number: 8000
